name: Python CI

# Настроим события, которые будут запускать процесс CI/CD
on:
  push:
    branches:
      - main  # запустится, когда ты сделаешь push в ветку main
  pull_request:
    branches:
      - main  # запустится, когда будет pull request в main

jobs:
  test:
    runs-on: ubuntu-latest  # это говорит, что тесты будут запускаться на виртуальной машине Ubuntu

    steps:
      # Шаг 1: клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # можешь указать версию Python, которая тебе нужна

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Шаг 4: Запускаем тесты
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/ --maxfail=1 --disable-warnings -v

      # Шаг 5: Логирование
      - name: Generate HTML report
        run: |
          source venv/bin/activate
          pytest tests/ --html=report.html --maxfail=1 --disable-warnings -v
          mv report.html $GITHUB_WORKSPACE/